// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppTest() {
  return window['go']['entry']['Application']['AppTest']();
}

export function DisableApp(arg1) {
  return window['go']['entry']['Application']['DisableApp'](arg1);
}

export function EnableApp(arg1) {
  return window['go']['entry']['Application']['EnableApp'](arg1);
}

export function EventTest() {
  return window['go']['entry']['Application']['EventTest']();
}

export function Free() {
  return window['go']['entry']['Application']['Free']();
}

export function GetAdbDir() {
  return window['go']['entry']['Application']['GetAdbDir']();
}

export function GetAppDir() {
  return window['go']['entry']['Application']['GetAppDir']();
}

export function GetLogDir() {
  return window['go']['entry']['Application']['GetLogDir']();
}

export function Greet(arg1) {
  return window['go']['entry']['Application']['Greet'](arg1);
}

export function InstallAdb() {
  return window['go']['entry']['Application']['InstallAdb']();
}

export function InstallExistingApp(arg1, arg2) {
  return window['go']['entry']['Application']['InstallExistingApp'](arg1, arg2);
}

export function ListApps(arg1) {
  return window['go']['entry']['Application']['ListApps'](arg1);
}

export function ProcessTest() {
  return window['go']['entry']['Application']['ProcessTest']();
}

export function RemoveAdb() {
  return window['go']['entry']['Application']['RemoveAdb']();
}

export function RemoveLog() {
  return window['go']['entry']['Application']['RemoveLog']();
}

export function Top() {
  return window['go']['entry']['Application']['Top']();
}

export function UninstallApp(arg1, arg2) {
  return window['go']['entry']['Application']['UninstallApp'](arg1, arg2);
}

export function WaitForDevice() {
  return window['go']['entry']['Application']['WaitForDevice']();
}
