// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AppTest():Promise<models.App>;

export function DisableApp(arg1:string):Promise<boolean>;

export function EnableApp(arg1:string):Promise<boolean>;

export function EventTest():Promise<models.EventData>;

export function Free():Promise<string>;

export function GetAdbDir():Promise<models.DirModel>;

export function GetAppDir():Promise<string>;

export function GetLogDir():Promise<models.DirModel>;

export function Greet(arg1:string):Promise<string>;

export function InstallAdb():Promise<boolean>;

export function InstallExistingApp(arg1:string,arg2:Array<string>):Promise<boolean>;

export function ListApps(arg1:number):Promise<void>;

export function ProcessTest():Promise<models.Process>;

export function RemoveAdb():Promise<void>;

export function RemoveLog():Promise<void>;

export function Top():Promise<models.TopInfo>;

export function UninstallApp(arg1:string,arg2:Array<string>):Promise<boolean>;

export function WaitForDevice():Promise<Array<models.Device>>;
