// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppExposed() {
  return window['go']['entry']['Application']['AppExposed']();
}

export function EventExposed() {
  return window['go']['entry']['Application']['EventExposed']();
}

export function Free() {
  return window['go']['entry']['Application']['Free']();
}

export function GetAdbDir() {
  return window['go']['entry']['Application']['GetAdbDir']();
}

export function GetAppDir() {
  return window['go']['entry']['Application']['GetAppDir']();
}

export function GetLogDir() {
  return window['go']['entry']['Application']['GetLogDir']();
}

export function Greet(arg1) {
  return window['go']['entry']['Application']['Greet'](arg1);
}

export function InstallAdb() {
  return window['go']['entry']['Application']['InstallAdb']();
}

export function ProcessExposed() {
  return window['go']['entry']['Application']['ProcessExposed']();
}

export function RemoveAdb() {
  return window['go']['entry']['Application']['RemoveAdb']();
}

export function RemoveLog() {
  return window['go']['entry']['Application']['RemoveLog']();
}

export function Top() {
  return window['go']['entry']['Application']['Top']();
}

export function WaitForDevice() {
  return window['go']['entry']['Application']['WaitForDevice']();
}
