// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppDir() {
  return window['go']['entry']['Application']['GetAppDir']();
}

export function Greet(arg1) {
  return window['go']['entry']['Application']['Greet'](arg1);
}

export function InstallAdb() {
  return window['go']['entry']['Application']['InstallAdb']();
}

export function InstallExistingApp(arg1, arg2) {
  return window['go']['entry']['Application']['InstallExistingApp'](arg1, arg2);
}

export function ListApps() {
  return window['go']['entry']['Application']['ListApps']();
}

export function ListApps1() {
  return window['go']['entry']['Application']['ListApps1']();
}

export function UninstallApp(arg1, arg2) {
  return window['go']['entry']['Application']['UninstallApp'](arg1, arg2);
}

export function WaitForDevice() {
  return window['go']['entry']['Application']['WaitForDevice']();
}
