// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableApp(arg1) {
  return window['go']['entry']['PackageManager']['DisableApp'](arg1);
}

export function EnableApp(arg1) {
  return window['go']['entry']['PackageManager']['EnableApp'](arg1);
}

export function InstallExistingApp(arg1, arg2) {
  return window['go']['entry']['PackageManager']['InstallExistingApp'](arg1, arg2);
}

export function ListApps(arg1) {
  return window['go']['entry']['PackageManager']['ListApps'](arg1);
}

export function ListModuleApps(arg1, arg2) {
  return window['go']['entry']['PackageManager']['ListModuleApps'](arg1, arg2);
}

export function ListModules(arg1) {
  return window['go']['entry']['PackageManager']['ListModules'](arg1);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['entry']['PackageManager']['UninstallApp'](arg1, arg2);
}
